-- Edroll WhatsApp Hub schema.
-- Runs unchanged on embedded Postgres (PGlite) and on PostgreSQL/Supabase.
-- All ids are generated by the application, so no extensions are required.

create table if not exists contacts (
  id           uuid primary key,
  wa_id        text not null unique,          -- E.164 phone number, no '+'
  profile_name text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table if not exists conversations (
  id                     uuid primary key,
  contact_id             uuid not null references contacts(id) on delete cascade,
  status                 text not null default 'open',
  last_message_at        timestamptz,
  last_message_direction text,
  last_inbound_at        timestamptz,
  first_inbound_at       timestamptz,
  first_response_at      timestamptz,
  first_response_seconds integer,
  closed_at              timestamptz,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

-- Prototype rule: one conversation per contact, reopened when they write again.
create unique index if not exists conversations_contact_uniq on conversations (contact_id);
create index if not exists conversations_last_message_idx on conversations (last_message_at desc nulls last);

create table if not exists messages (
  id                uuid primary key,
  conversation_id   uuid not null references conversations(id) on delete cascade,
  wa_message_id     text unique,               -- Meta "wamid..." (null while unknown)
  direction         text not null check (direction in ('inbound', 'outbound')),
  type              text not null default 'text',
  body              text,
  status            text not null default 'received',
  status_updated_at timestamptz,
  error             jsonb,
  meta              jsonb,
  created_at        timestamptz not null default now()
);

create index if not exists messages_conversation_idx on messages (conversation_id, created_at);
create index if not exists messages_wa_id_idx on messages (wa_message_id);

create table if not exists webhook_events (
  id              bigserial primary key,
  received_at     timestamptz not null default now(),
  source          text not null default 'meta',   -- meta | simulator
  signature_valid boolean,                        -- null when no app secret is configured
  payload         jsonb,
  handled         integer not null default 0,
  error           text
);

create index if not exists webhook_events_received_idx on webhook_events (received_at desc);
